// Compatibility of registerPasswordVerifier with REAL Contember password hashes.
//
// Contember hashes with `bcryptjs` at cost 10 (engine-http/src/providers.ts:
// `bcrypt: async (value) => await bcrypt.hash(value, 10)`), so the hashes produced here
// are byte-identical in format to the ones sitting in a Contember `tenant.person` table.
//
// BOTH prefixes occur in the wild and must verify: bcryptjs 2.x emits `$2a$`, while a
// row checked from a live Contember deployment carried `$2b$` (a newer bcryptjs). An
// import script must therefore not filter on either prefix — `bcrypt$` is what selects
// the verifier, and bcrypt.compare handles the rest.
//
// This is a unit test on the verification path; upgrade-on-login is covered end-to-end
// by test/suites/auth-legacy-hash.ts.

import { expect, test } from "bun:test";
import bcrypt from "bcryptjs";
import { isForeignHash, registerPasswordVerifier, verifyPassword } from "../packages/auth/src/index";

// Exactly what an app migrating off Contember registers.
registerPasswordVerifier("bcrypt", (password, payload) => bcrypt.compare(password, payload));

/** How an import script stores a row from `tenant.person.password_hash`. */
const imported = (contemberHash: string) => `bcrypt$${contemberHash}`;

// A fixed hash generated by bcryptjs@2.4.3 at cost 10 for "correct horse battery staple".
// Frozen as a fixture so this test keeps asserting against a known-good byte string even
// if the local bcryptjs version moves.
const FIXTURE_PASSWORD = "correct horse battery staple";
const FIXTURE_HASH = "$2a$10$J4J89A6ZuER5a88.ywYGce5vc96LYryHSLAB/LDKVwXVUGT70.946";

test("bcryptjs 2.4.3 at cost 10 emits the $2a$ form Contember stores", () => {
  const h = bcrypt.hashSync("password123", 10);
  expect(h.startsWith("$2a$10$")).toBe(true);
  expect(h.length).toBe(60);
});

test("a freshly generated Contember-style hash verifies through pramen", async () => {
  const contemberHash = await bcrypt.hash("password123", 10);
  expect(await verifyPassword("password123", imported(contemberHash))).toBe(true);
  expect(await verifyPassword("password124", imported(contemberHash))).toBe(false);
  expect(await verifyPassword("", imported(contemberHash))).toBe(false);
});

test("a frozen $2a$ fixture verifies (guards against a bcryptjs upgrade changing behaviour)", async () => {
  expect(bcrypt.compareSync(FIXTURE_PASSWORD, FIXTURE_HASH)).toBe(true); // sanity: the fixture is real
  expect(await verifyPassword(FIXTURE_PASSWORD, imported(FIXTURE_HASH))).toBe(true);
  expect(await verifyPassword("wrong", imported(FIXTURE_HASH))).toBe(false);
});

test("the $2b$ variant verifies too — this is what a live Contember tenant DB holds", async () => {
  // A row read from a production Contember deployment was `$2b$10$…` (60 chars), which
  // also matches what SignUpMutationResolver accepts on its import path.
  const b = (await bcrypt.hash("password123", 10)).replace(/^\$2a\$/, "$2b$");
  expect(b.startsWith("$2b$")).toBe(true);
  expect(await verifyPassword("password123", imported(b))).toBe(true);
  expect(await verifyPassword("nope", imported(b))).toBe(false);
});

test("non-ASCII and long passwords round-trip", async () => {
  for (const pw of ["heslo–ěščřžýáí", "🧘‍♀️ yoga 🧘", "x".repeat(72)]) {
    const h = await bcrypt.hash(pw, 10);
    expect(await verifyPassword(pw, imported(h))).toBe(true);
  }
});

test("a corrupt payload fails closed rather than throwing", async () => {
  expect(await verifyPassword("password123", "bcrypt$not-a-bcrypt-hash")).toBe(false);
  expect(await verifyPassword("password123", "bcrypt$")).toBe(false);
  expect(await verifyPassword("password123", "bcrypt$$2a$10$truncated")).toBe(false);
});

test("an unregistered scheme never verifies", async () => {
  const h = await bcrypt.hash("password123", 10);
  expect(await verifyPassword("password123", `md5$${h}`)).toBe(false);
});

test("imported hashes are flagged for upgrade, PBKDF2 ones are not", () => {
  expect(isForeignHash(imported(FIXTURE_HASH))).toBe(true);
  expect(isForeignHash("pbkdf2$sha256$600000$c2FsdA==$aGFzaA==")).toBe(false);
});

test("cost 10 verification stays within a sane budget for a Worker", async () => {
  const h = await bcrypt.hash("password123", 10);
  const t0 = performance.now();
  await verifyPassword("password123", imported(h));
  const ms = performance.now() - t0;
  // Informational bound, not a benchmark: pure-JS bcrypt at cost 10 should be well
  // inside a DO's relaxed CPU allowance. Generous so it can't flake on a loaded CI box.
  expect(ms).toBeLessThan(2000);
  console.log(`      bcrypt cost-10 verify: ${ms.toFixed(0)}ms`);
});
